#!/bin/sh
# leg20231128
#
# Poor mans unit test framework
#

: ${VERBOSE:=}
FLISP=../flisp


[ "$1" = "-?" ] && {
    cat <<EOF
Femto test suite

available tests:

$(
    for TESTFILE in *.test; do
        printf "\t%s\t%s\n" "$TESTFILE" "$(head -1 $TESTFILE)"
    done
)

Run all tests:  $0
Run some tests: $0 [test ..]
This help:      $0 -?

EOF
    exit
}

# print tap header line
tap() {
    [ "$1" ] && {
	echo TAP version 14
	echo 1..$1
	echo \# $test
    } ||
	trap '[ $? = 0 ] || echo Bail out!; echo 1..$TEST' EXIT
}

# create tap output line. Check $? for success
ok () {
    [ $? != 0 ] && printf "not " && OK=1 || OK=0
    TEST=$((TEST+1)); echo ok $TEST - $@; return $OK
}

# - - -

[ $# = 0 ] && set -- *.test

export FLISP_DEBUG=f.log

# pipe expr $IN to fLisp, extract $1 last values of output, default 1. Filters trailing 't.
# Compare output with $OUT
flisp_expr () {
    [ "$( echo -n "$IN" | $FLISP | tail -n ${1:-5})" = "$OUT" ]
}
flisp_err () {
    echo -n "$IN" | $FLISP 2>&1 | tail -n ${1:-5} |{
	read PRE REST
	: $PRE
	: $REST
	MSG=${REST#*, }
	[ "$OBJ" ] && {
	    EOBJ=${REST%%\',*}
	    EOBJ=${EOBJ#\'}
	    [ "$PRE" = "error:" -a "$MSG" = "$ERR" -a "$OBJ" = "$EOBJ" ]
	    RC=$? ERR= OBJ=
	    return $RC
	}
	[ "$PRE" = "error:" -a "$MSG" = "$ERR" ]
	RC=$? PRE= OBJ=
	return $RC
    }
}

femto_expr () {
    [ "$( echo -n "$IN" | FEMTO_BATCH=1 FEMTORC=- FEMTOLIB=$FLISP ../femto | tail -n $(($1+3)) )" = "$OUT
t" ]
}
femto_err () {
    [ "$( echo -n "$IN" | FEMTO_BATCH=1 FEMTORC=- FEMTOLIB=$FLISP ../femto | tail -n $(($1+3)) )" = "$OUT
nil" ]
}

if [ "$SUMMARY" ]; then SUMMARY=./tapview; else SUMMARY=cat; fi

for test; do  (
    #mkdir -p tmp
    #rm -rf tmp/*

    export FEMTOLIB=../lisp
    export FLISPLIB=../lisp
    echo testsuite: $test
    [ "$VERBOSE" ] && set -x
    . ./${test} | $SUMMARY
    set +x
); done
#rm -rf tmp
